#!/usr/bin/env sh

hg clone https://vim.googlecode.com/hg/ vim
cd vim
./configure --enable-pythoninterp --enable-python3interp --enable-rubyinterp --enable-multibyte --with-x
make && sudo make install
