#!/usr/bin/env sh

git clone git://github.com/b4winckler/vim.git
cd vim
./configure --enable-pythoninterp --enable-python3interp --enable-rubyinterp --enable-multibyte --with-x
make && sudo make install
